qna_model:
  model: "gemini-1.5-pro"
  temperature: 0.8
  top_p: 0.6
  max_tokens: 2000
embedding:
  model: "indobenchmark/indobert-base-p1"
  dimension: 768
chunk_strategy: 
  chunk_size: 500
  chunk_overlap: 10
vector_search_strategy:
  method: "similarity"
  k: 3